---
title: "ISDLT WITH S VARIATION AND SOCIALLY D"
output: html_document
---
  
  
# ISDLT Estimator 
# S = GAMMA
# C1,C2 = NORMAL



```{r}



library(ggplot2)
library(MASS)   # mvrnorm

m <- 500
ns <- c(100, 500)

p_values <- c(0.25, 0.5, 0.75)

# separate spreads for C1 and C2
sdC1_vals <- c(0.05, 0.10, 0.5)
sdC2_vals <- c(0.05, 0.25, 0.5)

S_grid <- seq(0, 4, 0.1)
k <- length(S_grid)

CASE_LABEL <- "SGAMMA_CNORM"

# rho levels
rho_values <- c(-0.5, 0, 0.5)

ALL_RESULTS <- data.frame()

for (n in ns) {
  for (pA in p_values) {
    for (sdC1 in sdC1_vals) {
      for (sdC2 in sdC2_vals) {
        for (rho in rho_values) {

          F_hat_store    <- matrix(NA, nrow = m, ncol = k)
          F_dir_store    <- matrix(NA, nrow = m, ncol = k)
          F_dir_sd_store <- matrix(NA, nrow = m, ncol = k)

          for (i in 1:m) {

            Sigma <- matrix(c(1,   rho, rho,
                              rho, 1,   0,
                              rho, 0,   1),
                            3, 3, byrow = TRUE)

            Z <- mvrnorm(n = n, mu = c(0, 0, 0), Sigma = Sigma)

            U1 <- pnorm(Z[,1])
            S  <- qgamma(U1, shape = 3, rate = 2)

            C1 <- 0.25 + sdC1 * Z[,2]
            C2 <- 0.25 + sdC2 * Z[,3]

            G <- rbinom(n, size = 1, prob = pA)

            Y1 <- ifelse(G == 1, S + C1, C1)
            Y2 <- ifelse(G == 1, C2,     S + C2)

            A_Y1 <- Y1[G == 1];  B_Y1 <- Y1[G == 0]
            A_Y2 <- Y2[G == 1];  B_Y2 <- Y2[G == 0]

            F_dir <- sapply(S_grid, function(s) mean(S <= s))

            shift_amt <- 0.05 * sd(S)
            F_dir_sd  <- pmin(pmax(F_dir + shift_amt, 0), 1)

            F1_Y1 <- function(y) mean(A_Y1 <= y)
            F0_Y1 <- function(y) mean(B_Y1 <= y)

            F_raw_1 <- sapply(S_grid, function(s) {
              inner_vals <- sapply(B_Y1, function(Yi) F1_Y1(s + Yi) - F0_Y1(Yi))
              mean(inner_vals) + 0.5
            })

            F1_Y2 <- function(y) mean(B_Y2 <= y)
            F0_Y2 <- function(y) mean(A_Y2 <= y)

            F_raw_2 <- sapply(S_grid, function(s) {
              inner_vals <- sapply(A_Y2, function(Yi) F1_Y2(s + Yi) - F0_Y2(Yi))
              mean(inner_vals) + 0.5
            })

            F_hat <- pmin(pmax(0.5 * (F_raw_1 + F_raw_2), 0), 1)

            F_dir_store[i, ]    <- F_dir
            F_dir_sd_store[i, ] <- F_dir_sd
            F_hat_store[i, ]    <- F_hat
          }

          F_true  <- pgamma(S_grid, shape = 3, rate = 2)
          TRUE_mat <- matrix(F_true, m, k, byrow = TRUE)

          avg_F_dir    <- colMeans(F_dir_store)
          avg_F_dir_sd <- colMeans(F_dir_sd_store)
          avg_F_hat    <- colMeans(F_hat_store)

          bias_dir    <- colMeans(F_dir_store - TRUE_mat)
          bias_dir_sd <- colMeans(F_dir_sd_store - TRUE_mat)
          bias_hat    <- colMeans(F_hat_store - TRUE_mat)

          mse_dir    <- colMeans((F_dir_store - TRUE_mat)^2)
          mse_dir_sd <- colMeans((F_dir_sd_store - TRUE_mat)^2)
          mse_hat    <- colMeans((F_hat_store - TRUE_mat)^2)

          var_dir    <- apply(F_dir_store, 2, var)
          var_dir_sd <- apply(F_dir_sd_store, 2, var)
          var_hat    <- apply(F_hat_store, 2, var)

          results <- data.frame(
            n = n,
            pA = pA,
            sdC1 = sdC1,
            sdC2 = sdC2,
            rho = rho,
            s = S_grid,

            F_true = round(F_true, 6),

            avg_F_dir    = round(avg_F_dir, 6),
            avg_F_dir_sd = round(avg_F_dir_sd, 6),
            avg_F_hat    = round(avg_F_hat, 6),

            bias_dir    = round(bias_dir, 6),
            bias_dir_sd = round(bias_dir_sd, 6),
            bias_hat    = round(bias_hat, 6),

            mse_dir    = round(mse_dir, 6),
            mse_dir_sd = round(mse_dir_sd, 6),
            mse_hat    = round(mse_hat, 6),

            var_dir    = round(var_dir, 6),
            var_dir_sd = round(var_dir_sd, 6),
            var_hat    = round(var_hat, 6)
          )

          write.csv(results,
                    paste0("ISDLT_n", n,
                           "_pA", pA,
                           "_sdC1", sdC1, "_sdC2", sdC2,
                           "_rho", rho,
                           "_baseS_",
                           CASE_LABEL, "_withSD.csv"),
                    row.names = FALSE)

          ALL_RESULTS <- rbind(ALL_RESULTS, results)

        }
      }
    }
  }
}

plot_data_ISDLT_SGAMMA_CNORM <- rbind(
  data.frame(ALL_RESULTS, estimator = "dir",
             bias = ALL_RESULTS$bias_dir,
             mse  = ALL_RESULTS$mse_dir,
             var  = ALL_RESULTS$var_dir),

  data.frame(ALL_RESULTS, estimator = "dir_sd",
             bias = ALL_RESULTS$bias_dir_sd,
             mse  = ALL_RESULTS$mse_dir_sd,
             var  = ALL_RESULTS$var_dir_sd),

  data.frame(ALL_RESULTS, estimator = "hat",
             bias = ALL_RESULTS$bias_hat,
             mse  = ALL_RESULTS$mse_hat,
             var  = ALL_RESULTS$var_hat)
)

write.csv(plot_data_ISDLT_SGAMMA_CNORM,
          paste0("ISDLT_ALL_plot_data_", CASE_LABEL, "_rho_n_baseS_withSD.csv"),
          row.names = FALSE)


```








```{r}



plot_data_ISDLT_SGAMMA_CNORM$n <- factor(
  plot_data_ISDLT_SGAMMA_CNORM$n,
  levels = c(100, 500),
  labels = c("n = 100", "n = 500")
)

plot_data_ISDLT_SGAMMA_CNORM$rho <- factor(
  plot_data_ISDLT_SGAMMA_CNORM$rho,
  levels = c(-0.5, 0, 0.5),
  labels = c("rho = -0.5", "rho = 0", "rho = 0.5")
)

plot_data_ISDLT_SGAMMA_CNORM$pA <- factor(
  plot_data_ISDLT_SGAMMA_CNORM$pA,
  levels = c(0.25, 0.5, 0.75)
)

plot_data_ISDLT_SGAMMA_CNORM$sdC1 <- factor(
  plot_data_ISDLT_SGAMMA_CNORM$sdC1,
  levels = c(0.05, 0.10, 0.5)
)

plot_data_ISDLT_SGAMMA_CNORM$sdC2 <- factor(
  plot_data_ISDLT_SGAMMA_CNORM$sdC2,
  levels = c(0.05, 0.25, 0.5)
)

plot_data_ISDLT_SGAMMA_CNORM$C_label <- factor(
  paste0(
    "C1 = ", plot_data_ISDLT_SGAMMA_CNORM$sdC1,
    ", C2 = ", plot_data_ISDLT_SGAMMA_CNORM$sdC2
  )
)

# legend labels
plot_data_ISDLT_SGAMMA_CNORM$estimator <- factor(
  plot_data_ISDLT_SGAMMA_CNORM$estimator,
  levels = c("dir", "dir_sd", "hat"),
  labels = c("Direct (clean)", "Direct + SD (under)", "ISDLT")
)

LINE_W <- 1.1

for (pp in levels(plot_data_ISDLT_SGAMMA_CNORM$pA)) {
  for (nn in levels(plot_data_ISDLT_SGAMMA_CNORM$n)) {

    pd <- subset(plot_data_ISDLT_SGAMMA_CNORM, pA == pp & n == nn)

    # Bias
    bias_plot <- ggplot(pd, aes(x = s, y = bias, color = estimator)) +
      geom_line(linewidth = LINE_W) +
      facet_grid(rho ~ C_label, scales = "free_y") +
      theme_bw(base_size = 16) +
      theme(
        legend.position = "top"
      ) +
      labs(
        x = "s",
        y = "Bias",
        color = ""
      )

    print(bias_plot)
    ggsave(
      paste0("ISDLT_Bias_SGAMMA_CNORM_pA_", pp, "_", gsub(" = ", "", nn), "_baseS_withSD.png"),
      plot = bias_plot, width = 18, height = 10, dpi = 300
    )

    # Variance
    var_plot <- ggplot(pd, aes(x = s, y = var, color = estimator)) +
      geom_line(linewidth = LINE_W) +
      facet_grid(rho ~ C_label, scales = "free_y") +
      theme_bw(base_size = 16) +
      theme(
        legend.position = "top"
      ) +
      labs(
        x = "s",
        y = "Variance",
        color = ""
      )

    print(var_plot)
    ggsave(
      paste0("ISDLT_Variance_SGAMMA_CNORM_pA_", pp, "_", gsub(" = ", "", nn), "_baseS_withSD.png"),
      plot = var_plot, width = 18, height = 10, dpi = 300
    )

    # MSE
    mse_plot <- ggplot(pd, aes(x = s, y = mse, color = estimator)) +
      geom_line(linewidth = LINE_W) +
      facet_grid(rho ~ C_label, scales = "free_y") +
      theme_bw(base_size = 16) +
      theme(
        legend.position = "top"
      ) +
      labs(
        x = "s",
        y = "MSE",
        color = ""
      )

    print(mse_plot)
    ggsave(
      paste0("ISDLT_MSE_SGAMMA_CNORM_pA_", pp, "_", gsub(" = ", "", nn), "_baseS_withSD.png"),
      plot = mse_plot, width = 18, height = 10, dpi = 300
    )
  }
}

```






 














# S = beta
# C = Uniform
# ISDLT 


```{r}




p_values <- c(0.25, 0.5, 0.75)

m <- 500
ns <- c(100, 500)

s_grid <- seq(0, 1, 0.05)
k <- length(s_grid)

# spreads for C1 and C2
maxc1_vals <- c(0.1, 0.25, 0.5)
maxc2_vals <- c(0.1, 0.25, 0.5)

CASE_LABEL <- "SBETA_CUNIFORM"

# rho levels
rho_values <- c(-0.5, 0, 0.5)

ALL_RESULTS <- data.frame()

for (n in ns) {
  for (p1 in p_values) {
    for (maxc1 in maxc1_vals) {
      for (maxc2 in maxc2_vals) {
        for (rho in rho_values) {

          F_hat_store    <- matrix(NA, nrow = m, ncol = k)
          F_dir_store    <- matrix(NA, nrow = m, ncol = k)
          F_dir_sd_store <- matrix(NA, nrow = m, ncol = k)

          for (i in 1:m) {

            Sigma <- matrix(c(1,   rho, rho,
                              rho, 1,   0,
                              rho, 0,   1),
                            3, 3, byrow = TRUE)

            Z <- mvrnorm(n = n, mu = c(0, 0, 0), Sigma = Sigma)

            U1 <- pnorm(Z[,1])
            U2 <- pnorm(Z[,2])
            U3 <- pnorm(Z[,3])

            S  <- qbeta(U1, 2, 5)
            C1 <- maxc1 * U2
            C2 <- maxc2 * U3

            G <- rbinom(n, 1, p1)

            Y1 <- ifelse(G == 1, S + C1, C1)
            Y2 <- ifelse(G == 1, C2,     S + C2)

            A_Y1 <- Y1[G == 1];  B_Y1 <- Y1[G == 0]
            A_Y2 <- Y2[G == 1];  B_Y2 <- Y2[G == 0]

            F_dir <- sapply(s_grid, function(s) mean(S <= s))

            shift_amt <- 0.05 * sd(S)
            F_dir_sd  <- pmin(pmax(F_dir + shift_amt, 0), 1)

            F1_Y1 <- function(y) mean(A_Y1 <= y)
            F0_Y1 <- function(y) mean(B_Y1 <= y)

            F_raw_1 <- sapply(s_grid, function(s) {
              inner_vals <- sapply(B_Y1, function(Yi)
                F1_Y1(s + Yi) - F0_Y1(Yi))
              mean(inner_vals) + 0.5
            })

            F1_Y2 <- function(y) mean(B_Y2 <= y)
            F0_Y2 <- function(y) mean(A_Y2 <= y)

            F_raw_2 <- sapply(s_grid, function(s) {
              inner_vals <- sapply(A_Y2, function(Yi)
                F1_Y2(s + Yi) - F0_Y2(Yi))
              mean(inner_vals) + 0.5
            })

            F_hat <- pmin(pmax(0.5 * (F_raw_1 + F_raw_2), 0), 1)

            F_dir_store[i, ]    <- F_dir
            F_dir_sd_store[i, ] <- F_dir_sd
            F_hat_store[i, ]    <- F_hat
          }

          F_true <- pbeta(s_grid, 2, 5)
          TRUE_mat <- matrix(F_true, m, k, byrow = TRUE)

          avg_F_dir    <- colMeans(F_dir_store)
          avg_F_dir_sd <- colMeans(F_dir_sd_store)
          avg_F_hat    <- colMeans(F_hat_store)

          bias_dir    <- colMeans(F_dir_store - TRUE_mat)
          bias_dir_sd <- colMeans(F_dir_sd_store - TRUE_mat)
          bias_hat    <- colMeans(F_hat_store - TRUE_mat)

          mse_dir     <- colMeans((F_dir_store - TRUE_mat)^2)
          mse_dir_sd  <- colMeans((F_dir_sd_store - TRUE_mat)^2)
          mse_hat     <- colMeans((F_hat_store - TRUE_mat)^2)

          var_dir     <- apply(F_dir_store, 2, var)
          var_dir_sd  <- apply(F_dir_sd_store, 2, var)
          var_hat     <- apply(F_hat_store, 2, var)

          results <- data.frame(
            n = n,
            p1 = p1,
            maxc1 = maxc1,
            maxc2 = maxc2,
            rho = rho,
            s = s_grid,

            F_true = round(F_true, 6),
            avg_F_dir = round(avg_F_dir, 6),
            avg_F_dir_sd = round(avg_F_dir_sd, 6),
            avg_F_hat = round(avg_F_hat, 6),

            bias_dir = round(bias_dir, 6),
            bias_dir_sd = round(bias_dir_sd, 6),
            bias_hat = round(bias_hat, 6),

            mse_dir  = round(mse_dir, 6),
            mse_dir_sd  = round(mse_dir_sd, 6),
            mse_hat  = round(mse_hat, 6),

            var_dir  = round(var_dir, 6),
            var_dir_sd  = round(var_dir_sd, 6),
            var_hat  = round(var_hat, 6)
          )

          write.csv(results,
                    paste0("ISDLT_n", n,
                           "_p", p1,
                           "_maxc1", maxc1,
                           "_maxc2", maxc2,
                           "_rho", rho,
                           "_baseS_",
                           CASE_LABEL, "_withSD.csv"),
                    row.names = FALSE)

          ALL_RESULTS <- rbind(ALL_RESULTS, results)

        }
      }
    }
  }
}

plot_data_ISDLT_SBETA_CUNIFORM <- rbind(
  data.frame(ALL_RESULTS,
             estimator = "dir",
             bias = ALL_RESULTS$bias_dir,
             mse = ALL_RESULTS$mse_dir,
             var = ALL_RESULTS$var_dir),

  data.frame(ALL_RESULTS,
             estimator = "dir_sd",
             bias = ALL_RESULTS$bias_dir_sd,
             mse = ALL_RESULTS$mse_dir_sd,
             var = ALL_RESULTS$var_dir_sd),

  data.frame(ALL_RESULTS,
             estimator = "hat",
             bias = ALL_RESULTS$bias_hat,
             mse = ALL_RESULTS$mse_hat,
             var = ALL_RESULTS$var_hat)
)

write.csv(plot_data_ISDLT_SBETA_CUNIFORM,
          paste0("ISDLT_ALL_plot_data_", CASE_LABEL, "_rho_n_baseS_withSD.csv"),
          row.names = FALSE)

```







```{r}


plot_data_ISDLT_SBETA_CUNIFORM$n <- factor(
  plot_data_ISDLT_SBETA_CUNIFORM$n,
  levels = c(100, 500),
  labels = c("n = 100", "n = 500")
)

plot_data_ISDLT_SBETA_CUNIFORM$rho <- factor(
  plot_data_ISDLT_SBETA_CUNIFORM$rho,
  levels = c(-0.5, 0, 0.5),
  labels = c("rho = -0.5", "rho = 0", "rho = 0.5")
)

plot_data_ISDLT_SBETA_CUNIFORM$p1 <- factor(
  plot_data_ISDLT_SBETA_CUNIFORM$p1,
  levels = c(0.25, 0.5, 0.75)
)

plot_data_ISDLT_SBETA_CUNIFORM$maxc1 <- factor(
  plot_data_ISDLT_SBETA_CUNIFORM$maxc1,
  levels = c(0.1, 0.25, 0.5)
)

plot_data_ISDLT_SBETA_CUNIFORM$maxc2 <- factor(
  plot_data_ISDLT_SBETA_CUNIFORM$maxc2,
  levels = c(0.1, 0.25, 0.5)
)

plot_data_ISDLT_SBETA_CUNIFORM$C_label <- factor(
  paste0(
    "C1 = ", plot_data_ISDLT_SBETA_CUNIFORM$maxc1,
    ", C2 = ", plot_data_ISDLT_SBETA_CUNIFORM$maxc2
  )
)

plot_data_ISDLT_SBETA_CUNIFORM$estimator <- factor(
  plot_data_ISDLT_SBETA_CUNIFORM$estimator,
  levels = c("dir", "dir_sd", "hat"),
  labels = c("Direct (clean)", "Direct + SD (under)", "ISDLT")
)

LINE_W <- 1.1

for (pp in unique(plot_data_ISDLT_SBETA_CUNIFORM$p1)) {
  for (nn in levels(plot_data_ISDLT_SBETA_CUNIFORM$n)) {

    pd <- subset(plot_data_ISDLT_SBETA_CUNIFORM, p1 == pp & n == nn)

    # Bias
    bias_plot <- ggplot(pd, aes(x = s, y = bias, color = estimator)) +
      geom_line(linewidth = LINE_W) +
      facet_grid(rho ~ C_label, scales = "free_y") +
      theme_bw(base_size = 16) +
      theme(
        legend.position = "top"
      ) +
      labs(
        x = "s",
        y = "Bias",
        color = ""
      )

    print(bias_plot)
    ggsave(
      paste0("ISDLT_Bias_SBETA_CUNIFORM_p1_", pp, "_", gsub(" = ", "", nn), "_baseS_withSD.png"),
      plot = bias_plot, width = 18, height = 10, dpi = 300
    )

    # Variance
    var_plot <- ggplot(pd, aes(x = s, y = var, color = estimator)) +
      geom_line(linewidth = LINE_W) +
      facet_grid(rho ~ C_label, scales = "free_y") +
      theme_bw(base_size = 16) +
      theme(
        legend.position = "top"
      ) +
      labs(
        x = "s",
        y = "Variance",
        color = ""
      )

    print(var_plot)
    ggsave(
      paste0("ISDLT_Variance_SBETA_CUNIFORM_p1_", pp, "_", gsub(" = ", "", nn), "_baseS_withSD.png"),
      plot = var_plot, width = 18, height = 10, dpi = 300
    )

    # MSE
    mse_plot <- ggplot(pd, aes(x = s, y = mse, color = estimator)) +
      geom_line(linewidth = LINE_W) +
      facet_grid(rho ~ C_label, scales = "free_y") +
      theme_bw(base_size = 16) +
      theme(
        legend.position = "top"
      ) +
      labs(
        x = "s",
        y = "MSE",
        color = ""
      )

    print(mse_plot)
    ggsave(
      paste0("ISDLT_MSE_SBETA_CUNIFORM_p1_", pp, "_", gsub(" = ", "", nn), "_baseS_withSD.png"),
      plot = mse_plot, width = 18, height = 10, dpi = 300
    )
  }
}

```







# S = CHI SQUARE DF 3
# C1, C2 = NORM



```{r}


p_values <- c(0.25, 0.5, 0.75)

m <- 500
ns <- c(100, 500)

# grid for Chi-square(3)
s_grid <- seq(0, 12, 0.5)
k <- length(s_grid)

# spreads for C1 and C2
sdC1_vals <- c(0.05, 0.10, 0.25)
sdC2_vals <- c(0.10, 0.25, 0.50)

CASE_LABEL <- "SCHISQ3_CNORM"

# rho levels
rho_values <- c(-0.5, 0, 0.5)

ALL_RESULTS <- data.frame()

for (n in ns) {
  for (p1 in p_values) {
    for (sdC1 in sdC1_vals) {
      for (sdC2 in sdC2_vals) {
        for (rho in rho_values) {

          F_hat_store    <- matrix(NA, nrow = m, ncol = k)
          F_dir_store    <- matrix(NA, nrow = m, ncol = k)
          F_dir_sd_store <- matrix(NA, nrow = m, ncol = k)

          for (i in 1:m) {

            Sigma <- matrix(c(1,   rho, rho,
                              rho, 1,   0,
                              rho, 0,   1),
                            3, 3, byrow = TRUE)

            Z <- mvrnorm(n = n, mu = c(0, 0, 0), Sigma = Sigma)

            U1 <- pnorm(Z[,1])

            S  <- qchisq(U1, df = 3)
            C1 <- 0.25 + sdC1 * Z[,2]
            C2 <- 0.25 + sdC2 * Z[,3]

            G <- rbinom(n, 1, p1)

            Y1 <- ifelse(G == 1, S + C1, C1)
            Y2 <- ifelse(G == 1, C2,     S + C2)

            A_Y1 <- Y1[G == 1];  B_Y1 <- Y1[G == 0]
            A_Y2 <- Y2[G == 1];  B_Y2 <- Y2[G == 0]

            F_dir <- sapply(s_grid, function(s) mean(S <= s))

            shift_amt <- 0.05 * sd(S)
            F_dir_sd  <- pmin(pmax(F_dir + shift_amt, 0), 1)

            F1_Y1 <- function(y) mean(A_Y1 <= y)
            F0_Y1 <- function(y) mean(B_Y1 <= y)

            F_raw_1 <- sapply(s_grid, function(s) {
              inner_vals <- sapply(B_Y1, function(Yi)
                F1_Y1(s + Yi) - F0_Y1(Yi))
              mean(inner_vals) + 0.5
            })

            F1_Y2 <- function(y) mean(B_Y2 <= y)
            F0_Y2 <- function(y) mean(A_Y2 <= y)

            F_raw_2 <- sapply(s_grid, function(s) {
              inner_vals <- sapply(A_Y2, function(Yi)
                F1_Y2(s + Yi) - F0_Y2(Yi))
              mean(inner_vals) + 0.5
            })

            F_hat <- pmin(pmax(0.5 * (F_raw_1 + F_raw_2), 0), 1)

            F_dir_store[i, ]    <- F_dir
            F_dir_sd_store[i, ] <- F_dir_sd
            F_hat_store[i, ]    <- F_hat
          }

          F_true <- pchisq(s_grid, df = 3)
          TRUE_mat <- matrix(F_true, m, k, byrow = TRUE)

          avg_F_dir    <- colMeans(F_dir_store)
          avg_F_dir_sd <- colMeans(F_dir_sd_store)
          avg_F_hat    <- colMeans(F_hat_store)

          bias_dir    <- colMeans(F_dir_store - TRUE_mat)
          bias_dir_sd <- colMeans(F_dir_sd_store - TRUE_mat)
          bias_hat    <- colMeans(F_hat_store - TRUE_mat)

          mse_dir     <- colMeans((F_dir_store - TRUE_mat)^2)
          mse_dir_sd  <- colMeans((F_dir_sd_store - TRUE_mat)^2)
          mse_hat     <- colMeans((F_hat_store - TRUE_mat)^2)

          var_dir     <- apply(F_dir_store, 2, var)
          var_dir_sd  <- apply(F_dir_sd_store, 2, var)
          var_hat     <- apply(F_hat_store, 2, var)

          results <- data.frame(
            n = n,
            p1 = p1,
            sdC1 = sdC1,
            sdC2 = sdC2,
            rho = rho,
            s = s_grid,
            F_true = round(F_true, 6),
            avg_F_dir = round(avg_F_dir, 6),
            avg_F_dir_sd = round(avg_F_dir_sd, 6),
            avg_F_hat = round(avg_F_hat, 6),
            bias_dir = round(bias_dir, 6),
            bias_dir_sd = round(bias_dir_sd, 6),
            bias_hat = round(bias_hat, 6),
            mse_dir  = round(mse_dir, 6),
            mse_dir_sd  = round(mse_dir_sd, 6),
            mse_hat  = round(mse_hat, 6),
            var_dir  = round(var_dir, 6),
            var_dir_sd  = round(var_dir_sd, 6),
            var_hat  = round(var_hat, 6)
          )

          write.csv(results,
                    paste0("ISDLT_n", n,
                           "_p", p1,
                           "_sdC1", sdC1,
                           "_sdC2", sdC2,
                           "_rho", rho,
                           "_baseS_",
                           CASE_LABEL, "_withSD.csv"),
                    row.names = FALSE)

          ALL_RESULTS <- rbind(ALL_RESULTS, results)

        }
      }
    }
  }
}

plot_data_ISDLT_SCHISQ3_CNORM <- rbind(
  data.frame(ALL_RESULTS,
             estimator = "dir",
             bias = ALL_RESULTS$bias_dir,
             mse = ALL_RESULTS$mse_dir,
             var = ALL_RESULTS$var_dir),

  data.frame(ALL_RESULTS,
             estimator = "dir_sd",
             bias = ALL_RESULTS$bias_dir_sd,
             mse = ALL_RESULTS$mse_dir_sd,
             var = ALL_RESULTS$var_dir_sd),

  data.frame(ALL_RESULTS,
             estimator = "hat",
             bias = ALL_RESULTS$bias_hat,
             mse = ALL_RESULTS$mse_hat,
             var = ALL_RESULTS$var_hat)
)

write.csv(plot_data_ISDLT_SCHISQ3_CNORM,
          paste0("ISDLT_ALL_plot_data_", CASE_LABEL, "_rho_n_baseS_withSD.csv"),
          row.names = FALSE)


```






```{r}


plot_data_ISDLT_SCHISQ3_CNORM$n <- factor(
  plot_data_ISDLT_SCHISQ3_CNORM$n,
  levels = c(100, 500),
  labels = c("n = 100", "n = 500")
)

plot_data_ISDLT_SCHISQ3_CNORM$rho <- factor(
  plot_data_ISDLT_SCHISQ3_CNORM$rho,
  levels = c(-0.5, 0, 0.5),
  labels = c("rho = -0.5", "rho = 0", "rho = 0.5")
)

plot_data_ISDLT_SCHISQ3_CNORM$p1 <- factor(
  plot_data_ISDLT_SCHISQ3_CNORM$p1,
  levels = c(0.25, 0.5, 0.75)
)

plot_data_ISDLT_SCHISQ3_CNORM$sdC1 <- factor(
  plot_data_ISDLT_SCHISQ3_CNORM$sdC1,
  levels = c(0.05, 0.10, 0.25)
)

plot_data_ISDLT_SCHISQ3_CNORM$sdC2 <- factor(
  plot_data_ISDLT_SCHISQ3_CNORM$sdC2,
  levels = c(0.10, 0.25, 0.50)
)

plot_data_ISDLT_SCHISQ3_CNORM$C_label <- factor(
  paste0(
    "C1 = ", plot_data_ISDLT_SCHISQ3_CNORM$sdC1,
    ", C2 = ", plot_data_ISDLT_SCHISQ3_CNORM$sdC2
  )
)

plot_data_ISDLT_SCHISQ3_CNORM$estimator <- factor(
  plot_data_ISDLT_SCHISQ3_CNORM$estimator,
  levels = c("dir", "dir_sd", "hat"),
  labels = c("Direct (clean)", "Direct + SD (under)", "ISDLT")
)

LINE_W <- 1.1

for (pp in levels(plot_data_ISDLT_SCHISQ3_CNORM$p1)) {
  for (nn in levels(plot_data_ISDLT_SCHISQ3_CNORM$n)) {

    pd <- subset(plot_data_ISDLT_SCHISQ3_CNORM, p1 == pp & n == nn)

    # Bias
    bias_plot <- ggplot(pd, aes(x = s, y = bias, color = estimator)) +
      geom_line(linewidth = LINE_W) +
      facet_grid(rho ~ C_label, scales = "free_y") +
      theme_bw(base_size = 16) +
      theme(
        legend.position = "top"
      ) +
      labs(
        x = "s",
        y = "Bias",
        color = ""
      )

    print(bias_plot)
    ggsave(
      paste0("ISDLT_Bias_SCHISQ3_CNORM_p1_", pp, "_", gsub(" = ", "", nn), "_baseS_withSD.png"),
      plot = bias_plot, width = 18, height = 10, dpi = 300
    )

    # Variance
    var_plot <- ggplot(pd, aes(x = s, y = var, color = estimator)) +
      geom_line(linewidth = LINE_W) +
      facet_grid(rho ~ C_label, scales = "free_y") +
      theme_bw(base_size = 16) +
      theme(
        legend.position = "top"
      ) +
      labs(
        x = "s",
        y = "Variance",
        color = ""
      )

    print(var_plot)
    ggsave(
      paste0("ISDLT_Variance_SCHISQ3_CNORM_p1_", pp, "_", gsub(" = ", "", nn), "_baseS_withSD.png"),
      plot = var_plot, width = 18, height = 10, dpi = 300
    )

    # MSE
    mse_plot <- ggplot(pd, aes(x = s, y = mse, color = estimator)) +
      geom_line(linewidth = LINE_W) +
      facet_grid(rho ~ C_label, scales = "free_y") +
      theme_bw(base_size = 16) +
      theme(
        legend.position = "top"
      ) +
      labs(
        x = "s",
        y = "MSE",
        color = ""
      )

    print(mse_plot)
    ggsave(
      paste0("ISDLT_MSE_SCHISQ3_CNORM_p1_", pp, "_", gsub(" = ", "", nn), "_baseS_withSD.png"),
      plot = mse_plot, width = 18, height = 10, dpi = 300
    )
  }
}

```



